
# profiling:
#   enable_profiling: false

metrics:
  logger: tensorboard
  freq:
    loss: 10

# TODO: required by torchtitan
# https://github.com/pytorch/torchtitan/blob/2f1c814da071cc8ad165d00be6f9c1a66f8e1cce/torchtitan/distributed/utils.py#L265
comm:
  trace_buf_size: 0

model:
  name: llama3
  flavor: 8B
  hf_assets_path: /tmp/Meta-Llama-3.1-8B-Instruct

optimizer:
  name: AdamW
  lr: 1e-5
  eps: 1e-8

lr_scheduler:
  warmup_steps: 200

training:
  local_batch_size: 1
  seq_len: 2048
  max_norm: 1.0
  steps: 1000
  compile: false

validation:
  local_batch_size: 1
  freq: -1  # Change to a positive number to enable validation
  steps: 200  # Max steps to run validation. Validation disabled if negative.

dataset:
  path: yahma/alpaca-cleaned
  split: train[:95%]

dataset_val:
  path: yahma/alpaca-cleaned
  split: train[95%:]

parallelism:
  data_parallel_replicate_degree: 1
  data_parallel_shard_degree: -1
  tensor_parallel_degree: 1
  pipeline_parallel_degree: 1
  context_parallel_degree: 1
  expert_parallel_degree: 1
  disable_loss_parallel: false

checkpoint:
  enable_checkpoint: true
  folder: /tmp/Meta-Llama-3.1-8B-Instruct/saved_checkpoints
  initial_load_path:  /tmp/Meta-Llama-3.1-8B-Instruct/
  initial_load_in_hf: true
  last_save_in_hf: true
  interval: 500
  async_mode: "disabled"

activation_checkpoint:
  mode: selective
  selective_ac_option: op
