# Toy app Training Configuration

# Global configuration
group_size: 8
batch_size: 16
max_req_tokens: 512
max_res_tokens: 512
model: "Qwen/Qwen2.5-0.5B-Instruct"

# Dataset configuration
dataset:
  model: ${model}

# Policy configuration
policy:
  engine_config:
    model: ${model}
    tensor_parallel_size: 1
    pipeline_parallel_size: 1
    enforce_eager: false
  sampling_config:
    n: ${group_size}
    max_tokens: ${max_res_tokens}
    temperature: 1.0
    top_p: 1.0

# Trainer configuration
trainer:
  model_name: ${model}
  learning_rate: 1e-5

# Reference model configuration
ref_model:
  model_name: ${model}

# Replay buffer configuration
replay_buffer:
  batch_size: ${batch_size}
  max_policy_age: 1 # Async by 1
  dp_size: 1

services:
  dataset:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false
  policy:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: true
  trainer:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: true
  replay_buffer:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false
  reward_actor:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false
