# GRPO Training Configuration

# Global configuration
group_size: 8
batch_size: 16
max_req_tokens: 512
max_res_tokens: 512
model: "Qwen/Qwen3-1.7B"

# Dataset configuration
dataset:
  path: "openai/gsm8k"
  revision: "main"
  data_split: "train"
  streaming: true
  model: ${model}
  service:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false

# Policy configuration
policy:
  engine_config:
    model: ${model}
    tensor_parallel_size: 1
    pipeline_parallel_size: 1
    enforce_eager: false
  sampling_config:
    n: ${group_size}
    max_tokens: ${max_res_tokens}
    temperature: 1.0
    top_p: 1.0
  service:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: true

# Trainer configuration
trainer:
  model_name: ${model}
  learning_rate: 1e-5
  service:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: true

# Replay buffer configuration
replay_buffer:
  batch_size: ${batch_size}
  max_policy_age: 1 # Async by 1
  dp_size: 1
  service:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false

# Compute advantages configuration
compute_advantages:
  service:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false

# Reference model configuration
ref_model:
  service:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: true

# Reward actor configuration
reward_actor:
  service:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false
