name: Unit Test

on:
  pull_request:


jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install pytorch
        run: python -m pip install torch==2.9.0.dev20250826 --extra-index-url https://download.pytorch.org/whl/nightly/cpu
      - name: Install monarch
        run: python -m pip install monarch-no-torch==0.1.0.dev20250826 --find-links assets/ci
      - name: Install torchstore
        run: pip install assets/wheels/torchstore-0.1.0-py3-none-any.whl
      - name: Install torchtitan
        run: |
          pip install assets/wheels/torchtitan-0.1.0-py3-none-any.whl
          pip install tyro
      - name: Install dependencies
        run: python -m pip install --no-build-isolation -e ".[dev]"
      - name: Run unit tests with coverage
        # TODO add all tests
        run: pytest tests/unit_tests --cov=. --cov-report=xml --durations=20 -vv
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
